### ISSUE TITLE
Remove Exception

### ISSUE THREAD

**Issue by danbeck** [danbeck/physalis#16]
[info] m.BuildTask - >> git clone https://github.com/danbeck/greenrss.git --depth=1 /home/daniel/workspace/physalis/55c9a741-bae8-4caa-a840-a0aeed660dd1/c3c19e34-beb1-4d4f-a625-de12512e6080/ubuntu
[error] m.BuildTask - There was an exception
java.nio.file.NoSuchFileException: /home/daniel/workspace/physalis/55c9a741-bae8-4caa-a840-a0aeed660dd1/c3c19e34-beb1-4d4f-a625-de12512e6080/ubuntu/log.txt
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_40]
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_40]
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_40]
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_40]
    at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[na:1.8.0_40]

**Comment by danbeck** [comment]
Done
